- name: Configure DHCP snooping globally
  ansible.netcommon.cli_command:
    command: |
      system-view
      dhcp snooping enable
      dhcp snooping user-bind arp-detect enable
      dhcp snooping enable vlan {{ item.vlan_id }}
      return
  loop: "{{ dhcp_vlans }}"
  when: (dhcp_snooping | default(false))

- name: Configure trusted interfaces
  ansible.netcommon.cli_command:
    command: |
      system-view
      interface {{ item.name }}
      dhcp snooping trusted
      return
  loop: "{{ trusted_interfaces }}"
  when: (dhcp_snooping | default(false))

- name: Configure untrusted interfaces
  ansible.netcommon.cli_command:
    command: |
      system-view
      interface {{ item.name }}
      dhcp snooping enable
      dhcp snooping check dhcp-giaddr enable
      dhcp snooping check dhcp-request enable
      dhcp snooping user-bind max-number 20
      dhcp snooping check dhcp-chaddr enable
      return
  loop: "{{ untrusted_interfaces }}"
  when: (dhcp_snooping | default(false))

- name: Save configuration
  ansible.netcommon.cli_command:
    command: |
      save
      y