- name: Config timestamps setting for logs
  cisco.ios.ios_config:
    lines:
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone

- name: Config logging
  cisco.ios.ios_logging_global:
    config:
      hosts:
        - hostname: '{{ syslog }}'
        - hostname: '{{ syslog_backup }}'
          transport:
            udp:
              port: 2515

- name: Config source interface for logging
  cisco.ios.ios_config:
    lines:
      - logging source-interface {{ logging_ntp_source }}

- name: Check result
  cisco.ios.ios_command:
    commands: sh logging
  register: result

- name: Debug lines
  ansible.builtin.debug: 
    var: result.stdout_lines

- name: Save config
  cisco.ios.ios_command:
    commands: wr
